// Mocks generated by Mockito 5.4.2 from annotations
// in apod/test/list/bloc/picture_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:apod/data/apod_pager.dart' as _i4;
import 'package:apod/data/model/picture_entity.dart' as _i7;
import 'package:apod/data/picture_dao.dart' as _i3;
import 'package:apod/data/picture_repository.dart' as _i5;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePictureDao_1 extends _i1.SmartFake implements _i3.PictureDao {
  _FakePictureDao_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApodPager_2 extends _i1.SmartFake implements _i4.ApodPager {
  _FakeApodPager_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PictureRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPictureRepository extends _i1.Mock implements _i5.PictureRepository {
  MockPictureRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i2.Client);

  @override
  _i3.PictureDao get pictureDao => (super.noSuchMethod(
        Invocation.getter(#pictureDao),
        returnValue: _FakePictureDao_1(
          this,
          Invocation.getter(#pictureDao),
        ),
      ) as _i3.PictureDao);

  @override
  _i4.ApodPager get pager => (super.noSuchMethod(
        Invocation.getter(#pager),
        returnValue: _FakeApodPager_2(
          this,
          Invocation.getter(#pager),
        ),
      ) as _i4.ApodPager);

  @override
  _i6.Stream<List<_i7.PictureEntity>> getEntities() => (super.noSuchMethod(
        Invocation.method(
          #getEntities,
          [],
        ),
        returnValue: _i6.Stream<List<_i7.PictureEntity>>.empty(),
      ) as _i6.Stream<List<_i7.PictureEntity>>);

  @override
  _i6.Future<void> fetchNextPage() => (super.noSuchMethod(
        Invocation.method(
          #fetchNextPage,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
